version: "3"
services:
  server:
    image: github.com/ad/gocc:dev
    networks:
        testing_net:
            ipv4_address: 172.28.1.2
  client:
    image: github.com/ad/gozond:dev
    environment:
      GOZOND_GOCC: server:5000
      GOZOND_UUID: DOCOFFEE-BODE-ACED-CODE-DABBEDDECADE
    depends_on:
      - server
    networks:
        testing_net:
            ipv4_address: 172.28.1.3
  anotherclient:
    image: github.com/ad/gozond:dev
    environment:
      GOZOND_GOCC: server:5000
      GOZOND_UUID: ABADBABE-DODO-FACE-FEED-BOBBEDBAOBAB
    depends_on:
      - server
    networks:
        testing_net:
            ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16